// src/lib/invoice-layout/standard-fields.ts

export interface StandardInvoiceField {
  key: string;
  label: string;
  type: "text" | "number" | "date" | "dropdown";
  category: "Client" | "Invoice Details" | "Financials" | "Payment" | "Notes";
  isRequired: boolean;
  description: string;
}

export const STANDARD_INVOICE_FIELDS: StandardInvoiceField[] = [
  {
    key: "invoice_id",
    label: "Invoice Number",
    type: "text",
    category: "Invoice Details",
    isRequired: true,
    description: "Unique sequential invoice code (e.g. INV-2026-0001)",
  },
  {
    key: "date",
    label: "Invoice Date",
    type: "date",
    category: "Invoice Details",
    isRequired: true,
    description: "Issue date printed on invoice",
  },
  {
    key: "due_date",
    label: "Due Date",
    type: "date",
    category: "Invoice Details",
    isRequired: false,
    description: "Payment due date / settlement deadline",
  },
  {
    key: "legal_name",
    label: "Client / Legal Name",
    type: "text",
    category: "Client",
    isRequired: true,
    description: "Recipient customer or legal company entity name",
  },
  {
    key: "user_email",
    label: "Client Email",
    type: "text",
    category: "Client",
    isRequired: true,
    description: "Client contact email for delivery and receipt",
  },
  {
    key: "client_phone",
    label: "Client Phone",
    type: "text",
    category: "Client",
    isRequired: false,
    description: "Customer telephone contact number",
  },
  {
    key: "billing_address",
    label: "Billing Address",
    type: "text",
    category: "Client",
    isRequired: false,
    description: "Registered physical or tax address of the client",
  },
  {
    key: "project_name",
    label: "Project / Service Title",
    type: "text",
    category: "Invoice Details",
    isRequired: true,
    description: "Project title or headline description of work",
  },
  {
    key: "currency",
    label: "Currency",
    type: "dropdown",
    category: "Financials",
    isRequired: true,
    description: "Base currency code (e.g. LKR, USD, EUR, GBP, AUD)",
  },
  {
    key: "category",
    label: "Income Category",
    type: "dropdown",
    category: "Invoice Details",
    isRequired: false,
    description: "Accounting & revenue classification tag",
  },
  {
    key: "payment_status",
    label: "Payment Status",
    type: "dropdown",
    category: "Financials",
    isRequired: true,
    description: "Status: unpaid, partially paid, advance-paid, overdue, paid",
  },
  {
    key: "work_status",
    label: "Work Status",
    type: "dropdown",
    category: "Invoice Details",
    isRequired: false,
    description: "Project fulfillment progress (pending, in progress, completed)",
  },
  {
    key: "bank_account_id",
    label: "Bank Account Details",
    type: "dropdown",
    category: "Payment",
    isRequired: false,
    description: "Beneficiary bank account name, number, and branch",
  },
  {
    key: "line_items",
    label: "Line Items Table",
    type: "text",
    category: "Financials",
    isRequired: true,
    description: "Breakdown of item descriptions, quantities, unit prices & amounts",
  },
  {
    key: "subtotal",
    label: "Subtotal",
    type: "number",
    category: "Financials",
    isRequired: true,
    description: "Pre-tax, pre-discount sum of all line items",
  },
  {
    key: "discount",
    label: "Discount",
    type: "number",
    category: "Financials",
    isRequired: false,
    description: "Deduction or rebate subtracted from subtotal",
  },
  {
    key: "tax_rate",
    label: "Tax Rate (%)",
    type: "number",
    category: "Financials",
    isRequired: false,
    description: "Applicable VAT / SSCL / Sales tax percentage",
  },
  {
    key: "advance",
    label: "Advance Paid",
    type: "number",
    category: "Financials",
    isRequired: false,
    description: "Deposit or upfront payment already settled",
  },
  {
    key: "total_due",
    label: "Total Due / Balance",
    type: "number",
    category: "Financials",
    isRequired: true,
    description: "Net outstanding balance payable by the client",
  },
  {
    key: "notes",
    label: "Customer Notes",
    type: "text",
    category: "Notes",
    isRequired: false,
    description: "Customer remarks, instructions or thank-you message",
  },
  {
    key: "terms",
    label: "Terms & Conditions",
    type: "text",
    category: "Notes",
    isRequired: false,
    description: "Payment terms, overdue interest conditions, and policies",
  },
];
